2018:
  - type: input
    directory: 0
    path: "input/sensor/2018_input_sensor.csv"
    format: csv
2016:
  - type: daily
    directory: 1
    path: "input/2016_year"
    format: json
  - type: monthly
    directory: 0
    path: "input/2016_month/Monthlydata_mouth_2016_2016.json"
    format: json
  - type: yearly
    directory: 0
    path: ""
    format: json